import MoirePiSixthResonance
import MoireLqApplication
import MoireDirectionalArithmetic
import MoirePolygonFilling
import MoireSection2
import MoireDifferenceLaw
import MoireUpperFromLq
import MoireSection3GeometricResults
import MoireSection3
import MoireLatticeWords
import MoireEisenstein
import MoireGeometry
import MoireCounting
import MoireEndpoint
import MoireFibre
import MoireConcrete
import MoireSection2Results
import MoireCharacterisation
import MoirePiThirdTable
import MoireGraphGeometry
import MoireSpectralWeights
import MoirePathMeasure
import MoireGraphCoding
import MoireSection2Complete

-- This is a dependency audit, not a replacement for reviewing theorem scope.
#print axioms MoireSection2.allowedPiThird_zero
#print axioms MoireSection2.six_two_step_returns
#print axioms MoireLatticeWords.wordValue_injective
#print axioms MoireLatticeWords.rotation_mem_ratioClosure_of_finite_liveReachable
#print axioms MoireEisenstein.complexCoordinates_injective
#print axioms MoireEisenstein.rotation_mem_eisensteinField_of_finite_live_carries
#print axioms MoireGeometry.gasket_selfSimilar
#print axioms MoireGeometry.gasket_intersection_recursion
#print axioms MoireCounting.distinct_digits_do_not_count_pairs
#print axioms MoireCounting.piThirdGraphCount_even_ratio
#print axioms MoireEndpoint.legal_iff_endpoint_mem
#print axioms MoireFibre.zeroFibre_hausdorffDim
#print axioms MoireSection3.ae_upper_box_dimension_le
#print axioms MoireConcrete.finite_type_implies_commensurable
#print axioms MoireConcrete.gasket_zeroFibre_hausdorffDim
#print axioms MoireConcrete.manuscript_unlabelled_count_is_false
#print axioms MoireAngles.exp_mem_eisensteinField_iff_rational_halfAngle
#print axioms MoireAngles.exp_mem_eisensteinField_iff_coprime_parametrisation
#print axioms MoireDimension.isCompact_gasket
#print axioms MoireDimension.dimH_shiftedIntersection_recursion
#print axioms MoireFiniteType.field_implies_finite_liveReachable
#print axioms MoireFiniteType.finite_type_iff_resonant_of_nonempty
#print axioms MoireDeterminization.gasket_state_recursion
#print axioms MoireSection2Results.resonant_iff_rotated_lattice_inclusion
#print axioms MoireSection2Results.resonant_reachable_states_finite
#print axioms MoireSection2Results.resonant_angles_countable
#print axioms MoireNonempty.edge_mem_gasket
#print axioms MoireNonempty.initial_intersection_nonempty
#print axioms MoireDensity.closure_resonant_angles
#print axioms MoireCharacterisation.finite_type_iff_resonant
#print axioms MoireCharacterisation.finite_type_angles_countable
#print axioms MoireCharacterisation.closure_finite_type_angles
#print axioms MoirePiThirdGeometry.live_successor_iff
#print axioms MoirePiThirdGeometry.liveReachable_piThird_eq
#print axioms MoirePiThirdTable.reachableState_iff
#print axioms MoirePiThirdTable.geometric_table
#print axioms MoirePiThirdTable.adjacency_eq
#print axioms MoirePiThirdTable.geometric_matrix_spectral_radius
#print axioms MoireGraphGeometry.graph_distinct_edges_disjoint
#print axioms MoireGraphGeometry.stateIntersection_isCompact
#print axioms MoireSpectralWeights.exists_nonnegative_spectral_weights
#print axioms MoireSpectralWeights.path_probability_bound
#print axioms MoirePathMeasure.pathMeasure_probability
#print axioms MoireGraphCoding.addressPoint_mem_of_path
#print axioms MoireActualUpper.resonant_dimH_initial_le
#print axioms MoirePathCylinders.cylinder_measure_product
#print axioms MoirePathSupport.ae_good_paths
#print axioms MoireGeometricMeasure.ae_code_mem
#print axioms MoireSpectralMass.geometric_dyadic_ball_mass
#print axioms MoireMassDistribution.le_dimH_of_dyadic_mass
#print axioms MoireHausdorffEquality.hausdorff_dimension_eq
#print axioms MoireBoxDimension.lowerBoxDimension_le_upperBoxDimension
#print axioms MoireBoxEquality.box_dimensions_eq
#print axioms MoireSection2Complete.resonant_dimensions
#print axioms MoireSection2Complete.piThird_actual_spectral_radius
#print axioms MoireSection2Complete.piThird_dimensions
#print axioms MoireDifferenceMeasure.prefix_probability
#print axioms MoireDifferenceMeasure.prefix_event_probability
#print axioms MoireDifferenceMeasure.differenceMeasure_eq_product_law
#print axioms MoireDifferenceLaw.gasketMeasure_gasket
#print axioms MoireDifferenceLaw.differenceMeasure_eq_convolution
#print axioms MoireIntersectionCounting.count_le_small_ball
#print axioms MoireIntersectionCounting.intersectionCenters_cover
#print axioms MoireDyadicConcentration.sum_cell_mass
#print axioms MoireDyadicConcentration.small_ball_mass_le_moment
#print axioms MoireLqDimension.eventually_moment_le_exp
#print axioms MoireLqDimension.eventually_ball_mass_le_exp
#print axioms MoireUpperFromLq.upperBox_le_of_full_lq
#print axioms MoireUpperFromLq.ae_upperBox_le_of_ae_full_lq
#print axioms MoireSeparationGeometry.one_le_norm_lattice
#print axioms MoireSeparationGeometry.determinant_le_projections
#print axioms MoireAngularSublevel.sine_sublevel_volume
#print axioms MoireDeterminantSublevel.determinant_sublevel_volume
#print axioms MoireAlmostEveryProjection.ae_determinant_bound
#print axioms MoireSeparationPeriodicity.ae_difference_exponential_separation
#print axioms MoireSeparationPeriodicity.ae_projection_dichotomy
#print axioms MoireGasketDimension.gasket_dimH
#print axioms MoireSection3GeometricResults.upperBox_le_codimension_of_full_lq
#print axioms MoireSection3GeometricResults.ae_both_separation_lemmas
#print axioms MoireSection3GeometricResults.ae_upper_bound_of_analytic_input

#print axioms MoireBernoulliRecursion.prepend_law
#print axioms MoireBernoulliRecursion.gasketMeasure_selfSimilar
#print axioms MoireMeasureSimilarity.differenceMeasure_selfSimilar
#print axioms MoireHomogeneousSystem.cylinderCenter_vertex
#print axioms MoireHomogeneousSystem.cylinderCenter_difference
#print axioms MoireHomogeneousSystem.difference_selfSimilar
#print axioms MoireHomogeneousSystem.difference_separation
#print axioms MoireProjectedSystems.projected_separation
#print axioms MoireProjectedSystems.reflected_separation
#print axioms MoireProjectedSystems.projected_difference_convolution
#print axioms MoireLqApplication.projected_difference_full
#print axioms MoireLqApplication.difference_full
#print axioms MoireLqApplication.ae_upper_bound
#print axioms MoireDirectionalResonance.countable_directionallyResonant
#print axioms MoireDirectionalResonance.ae_not_directionallyResonant
#print axioms MoireDirectionalArithmetic.directionallyResonant_iff_slope
#print axioms MoireMeasureSupport.gasketMeasure_support
#print axioms MoireMeasureSupport.differenceMeasure_support
#print axioms MoireTriangleBoundary.boundary_subset_gasket
#print axioms MoirePolygonFilling.boundaries_meet
#print axioms MoirePolygonFilling.gasket_difference_eq_triangle_difference
#print axioms MoirePolygonFilling.differenceMeasure_support_polygon
#print axioms MoirePolygonFilling.support_convex
#print axioms MoirePolygonFilling.support_contains_zero
#print axioms MoirePolygonFilling.negative_gasket_difference_eq

#print axioms MoirePiSixthResonance.pi_sixth_directionallyResonant
#print axioms MoirePiSixthResonance.pi_sixth_not_resonant
