import MoireSection2
import MoireSection3
import MoireLatticeWords
import MoireEisenstein
import MoireGeometry
import MoireCounting
import MoireEndpoint
import MoireFibre
import MoireConcrete
import MoireSection2Results

-- This is a dependency audit, not a replacement for reviewing theorem scope.
#print axioms MoireSection2.allowedPiThird_zero
#print axioms MoireSection2.six_two_step_returns
#print axioms MoireLatticeWords.wordValue_injective
#print axioms MoireLatticeWords.rotation_mem_ratioClosure_of_finite_liveReachable
#print axioms MoireEisenstein.complexCoordinates_injective
#print axioms MoireEisenstein.rotation_mem_eisensteinField_of_finite_live_carries
#print axioms MoireGeometry.gasket_selfSimilar
#print axioms MoireGeometry.gasket_intersection_recursion
#print axioms MoireCounting.distinct_digits_do_not_count_pairs
#print axioms MoireCounting.piThirdGraphCount_even_ratio
#print axioms MoireEndpoint.legal_iff_endpoint_mem
#print axioms MoireFibre.zeroFibre_hausdorffDim
#print axioms MoireSection3.ae_upper_box_dimension_le
#print axioms MoireConcrete.finite_type_implies_commensurable
#print axioms MoireConcrete.gasket_zeroFibre_hausdorffDim
#print axioms MoireConcrete.manuscript_unlabelled_count_is_false
#print axioms MoireAngles.exp_mem_eisensteinField_iff_rational_halfAngle
#print axioms MoireAngles.exp_mem_eisensteinField_iff_coprime_parametrisation
#print axioms MoireDimension.isCompact_gasket
#print axioms MoireDimension.dimH_shiftedIntersection_recursion
#print axioms MoireFiniteType.field_implies_finite_liveReachable
#print axioms MoireFiniteType.finite_type_iff_resonant_of_nonempty
#print axioms MoireDeterminization.gasket_state_recursion
#print axioms MoireSection2Results.resonant_iff_rotated_lattice_inclusion
#print axioms MoireSection2Results.resonant_reachable_states_finite
#print axioms MoireSection2Results.resonant_angles_countable
